# Copyright 2019 Google Inc.  All Rights Reserved.

version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
# funlen triggers on test functions which it shouldn't
#    - funlen
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
#    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    dupl:
      threshold: 400
    lll:
      line-length: 170
    gocyclo:
      min-complexity: 30
    staticcheck:
      checks:
        - "all"
        - "-QF*"

  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - linters:
          - revive
        text: "var-naming: avoid"
    paths:
      - thirdparty/

formatters:
  enable:
    - gofmt
    - goimports

